### ISSUE TITLE
Übersicht

### ISSUE THREAD

**Issue by oliverpool** [packmas13/registration#10]
## 2. Nutzer Kontomanagement (StaVos, BeVos, Lagerleitung...) #12
- [x] Anmelden
- [x] Passwort ändern
- [x] Passwort Zurücksetzen

## 3. Teilnehmer Anmeldung
Jeder Nutzer, kann alle Stämme (/Bezirke) sehen und bearbeiten, wo er berechtigt ist:
- [x] Aktuelle Liste ansehen und bearbeiten #13
- [x] Neue Teilnehmer hinzufügen #13
- [x] Teilnehmer von der NaMi importierent #17
- [x] Teilnehmerliste exportieren #19
- [ ] E-Mail an alle Teilnehmer #16
- [ ] Stamm übersicht/Dashboard #18

- [ ] Teilnehmer abmelden
Der Nutzer kann neue Teilnehmer abmelden. Die abgemeldete Teilnehmer bleiben in der Teilnehmerliste (sind aber anders gekennzeichnet). In bestimmte Fälle wird auch der Betrag teilweise oder ganz erstattet (muss die Lagerleitung bestimmen)

## 4. Zeit- & Betragmanagement
- [ ] Anmeldungen sind möglich nur bis zu einem bestimmten Zeitpunkt
- [ ] Es gibt einen Frühbucherrabatt ?
- [ ] Abmeldung sind Zeitlich begrenzt (Erstattung abhängig von viele Faktoren?)
