### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ackxolotl** [packmas13/registration#4]
- [x] [Implement custom user model to enforce unique email addresses](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#specifying-a-custom-user-model)
- [ ] Check correctness of custom user model
- [ ] [Create custom permissions for models](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#custom-permissions)
- [x] Add attendance dates to `Participant` model
- [x] Add diet options to `Participant` model
- [ ] [Create a custom login page](https://stackoverflow.com/questions/35773576/django-custom-login-page/35779233#35779233)
- [ ] Create a password reset page (?)
- [ ] Add privacy statement
- [ ] Add imprint
- [ ] Add views and tests for `Participant` model
- [ ] Add views and tests for `Discount` model
- [ ] Add views and tests for `Payment` model
- [x] Add deprecation warning to linter tests: `python3 -Wa manage.py test`
- [ ] Add favicon
- [ ] Add logo to the [packmas13 organization](https://github.com/packmas13/)

**Comment by oliverpool** [comment]
## Initial user import:
- [ ] Add a way to import the initial users (`manage.py import users.csv` for instance)
In this file, there should be one user per line, with its email and troop
This file will generate the troop (if it doesn't exist yet), create the user (if it doesn't exist), add the user to the troop and send the user a welcome email (if it was just created), for the user to reset its password.
=> this should be tested with a fake .csv (the one containing the actual data should not be versioned inside git, for privacy reasons)

**Comment by oliverpool** [comment]
I have moved most TODOs to the github project: https://github.com/packmas13/registration/projects/1

My goal is to keep in `To Do` only the stuff that is well-enough defined, to be implemented without the need of feedback first.

I didn't add the ` Add views and tests for ... since I feel that they are to broad (should be more like: `add a page to register participants`)
